version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/connect
hooks:
  BeforeInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      runas: deploy
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 60
      runas: deploy
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 60
      runas: deploy
