db:
  image: postgres:9.4
  ports:
   - "5432"
web:
  build: .
  command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
  volumes:
   - .:/connect
  ports:
   - "3000:3000"
  links:
   - db
worker:
  build: .
  command: bundle exec rake jobs:work
  volumes:
   - .:/connect
  links:
   - db
