development: &default
  adapter: postgresql
  database: connect_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 10
  port: 5432
  timeout: 5000
  user: postgres

test:
  <<: *default
  database: connect_test
