search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/presenters"
    - "app/views"
    - "app/models"

ignore_unused:
  - activerecord.*
  - date.*
  - helpers.submit.*
  - jobvite_import.status.*
  - simple_form.*
  - time.*
  - titles.*
  - icims_candidate_import_mailer.*
